# syntax = docker/dockerfile:1

FROM python:3.9
WORKDIR /Immo-Eliza-Deployment
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
ENTRYPOINT ["python"]
CMD ["app.py", "--host = 0.0.0.0"]